# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SignalR-Swift-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SignalR-Swift-Example
  pod 'SignalRSwift', :git => 'https://github.com/irfangul10pearls/SignalR-Swift.git', :commit => 'eff3e4d3e7c5428611b1ee8a68522973179d8736'

  target 'SignalR-Swift-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
